shopt -s expand_aliases
alias ls="ls --color=auto"
alias ll="ls -l"
alias lla="ls -la"
alias df="df -Tha --total"

alias vn="vagrant nsidc"

alias h="history"

alias more='less -R'

alias dockrm='docker rm -v $(docker ps -aq -f status=exited)'
alias tmux='tmux -2'
