shopt -s expand_aliases
alias ll="ls -l"
alias lla="ls -la"
alias df="df -ha"

alias vn="vagrant nsidc"

alias h="history"

alias more='less -R'

# Clean up merged branches
alias gbc='git branch --merged | grep -v "\*" | xargs -n 1 git branch -d'

# Tell ipython to use VI bindings
alias ipython='ipython --TerminalInteractiveShell.editing_mode=vi'

# List executables in current bash environment
alias lsbin='echo $PATH | xargs -d: -i find {} -executable -type f'
