export TERM=xterm-256color

export VISUAL=vim
export EDITOR=vim
set -o vi

export PATH="$HOME/.rbenv/bin:$PATH"
export PATH="$HOME/miniconda2/bin:$PATH"

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"  # This loads nvm

eval "$(rbenv init -)"

export PS1="\[\e[0;32m\]\u\[\e[m\] \[\e[1;34m\]\w\[\e[m\] \[\e[1;32m\]\[\e[m\] \[\e[1;37m\] \n$ "

[ -f ~/.fzf.bash ] && source ~/.fzf.bash
