# export TERM=xterm-256color

export VISUAL=nvim
export EDITOR=nvim
export TERM=xterm-256color

# export PATH="$HOME/.rbenv/bin:$PATH"
# eval "$(rbenv init -)"

set -o vi

export PATH="/home/ekpyro/miniconda2/bin:$PATH"

. ~/.bash_aliases

[ -f ~/.fzf.bash ] && source ~/.fzf.bash
