shopt -s expand_aliases
alias ll="ls -l"
alias lla="ls -la"
alias df="df -ha"

alias vn="vagrant nsidc"

alias h="history"

alias more='less -R'

alias gbc='git branch --merged | grep -v "\*" | xargs -n 1 git branch -d'
alias ipython='ipython --TerminalInteractiveShell.editing_mode=vi'
